Make states fill_color="none" (transparent)
holoviz/geoviews pull request #643
Opened 2023-05-24 04:42 UTC by ahuang11

Closes https://github.com/holoviz/geoviews/issues/512 (not sure why I closed the previous PR; perhaps because it was stale).

Also not sure if it's a better choice to set fill_alpha vs fill_color.

I would like to skip importing and calling geoviews:
```
import pandas as pd
import hvplot.pandas
import geoviews as gv

df = pd.read_html(
    "https://mesonet.agron.iastate.edu/sites/networks.php?station=ORD&network=IL_ASOS"
)[1]
# make snake case
df.columns = df.columns.str.lower().str.replace(" ", "_")

map = df.hvplot.points(
    "longitude1",
    "latitude1",
    geo=True,
)

# overlay the map
states = gv.feature.states(fill_color="none")
map * states
```
<img width="223" alt="image" src="https://github.com/holoviz/geoviews/assets/15331990/f73b2076-bc9f-4076-a1e5-eb96d0039ed4">

And instead, do this:
```
import pandas as pd
import hvplot.pandas
import geoviews as gv

df = pd.read_html(
    "https://mesonet.agron.iastate.edu/sites/networks.php?station=ORD&network=IL_ASOS"
)[1]
# make snake case
df.columns = df.columns.str.lower().str.replace(" ", "_")

map = df.hvplot.points(
    "longitude1",
    "latitude1",
    geo=True,
    features=["states"]
)

# overlay the map
map
```

At the moment, it shows this:
<img width="216" alt="image" src="https://github.com/holoviz/geoviews/assets/15331990/7be06a92-09c2-4a3b-b0e5-ba2243ef157e">

2023-05-24 09:02 UTC, Hoxbro requested changes
If you update the `CHANGELOG.md` and `doc/releases.rst` with a comment about this PR today, I will add this to the next release. Maybe a small comment about this is a (small) breaking change. 

Using color makes sense to me. That will be the first thing coming to mind when wanting a background color, not the alpha. 

See here: https://github.com/holoviz/geoviews/pull/637/files

2023-05-24 19:46 UTC, ahuang11 commented
Okay done; feel free to make direct edits if needed!

2023-05-25 08:12 UTC, Hoxbro commented
Thank you for the quick turnaround.

2023-05-25 08:13 UTC, Hoxbro approved these changes

2023-05-25 08:13 UTC, merged

2023-05-25 16:43 UTC, ahuang11 commented
Thanks for getting this in! Can't wait to use it in hvplot!